# -*- coding: utf-8 -*-
"""week2_Python_in_class_work.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Reben80/Data110-22016/blob/main/week2_Python_in_class_work.ipynb
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Load the dataset
df = pd.read_csv('https://raw.githubusercontent.com/Noah-Baugh/Data110/main/datasets/happiness_2017.csv')

# 1. View the first few rows
print(df.head())

# 2. Get summary statistics
print(df.describe())

# 3. Check the shape (rows, columns)
print(df.shape)

# 4. View column names
print(df.columns)

# 5. Get data types and info
print(df.info())

# 6. Count unique values in the 'Country' column (or any other relevant column)
print(df['Country'].value_counts())

"""### Example 1: Happiness Score vs. Log GDP per Capita"""

# Scatter plot of Happiness Score vs Log GDP per Capita
plt.scatter(df['Log GDP per capita'], df['HappinessScore'])
plt.xlabel('Log GDP per Capita')
plt.ylabel('Happiness Score')
plt.title('Happiness Score vs Log GDP per Capita')
plt.show()

"""### Example 2: Happiness Score vs. Healthy Life Expectancy"""

# Scatter plot of Happiness Score vs Healthy Life Expectancy at Birth
plt.scatter(df['Healthy life expectancy at birth'], df['HappinessScore'], color='green')
plt.xlabel('Healthy Life Expectancy at Birth')
plt.ylabel('Happiness Score')
plt.title('Happiness Score vs Healthy Life Expectancy at Birth')
plt.show()

"""### Additional Tasks:
- **Happiness Score vs Social Support** (`Social support`)
- **Happiness Score vs Freedom to Make Life Choices** (`Freedom to make life choices`)
- **Happiness Score vs Generosity** (`Generosity`)

Update your code using the correct column names based on this.

### Extra Task:
Create **two scatter plots** using columns that do not have a meaningful relationship. For example, you might plot **Generosity** against **Healthy Life Expectancy**.
"""

plt.scatter(df['Social support'], df['HappinessScore'], color='red')
plt.xlabel('Social Support')
plt.ylabel('Happiness Score')
plt.title('Happiness Score vs Social Support')
plt.show()

# Your code related to Happiness Score vs Freedom to Make Life Choices (Freedom to make life choices) need to be here
plt.scatter(df['Freedom to make life choices'], df['HappinessScore'], color='blue')
plt.xlabel('Freedom to Make Life Choices')
plt.ylabel('Happiness Score')
plt.title('Happiness Score vs Freedom to Make Life Choices')
plt.show()

# Your code related to Happiness Score vs Generosity (Generosity) need to be here
plt.scatter(df['Generosity'], df['HappinessScore'], color='orange')
plt.xlabel('Generosity')
plt.ylabel('Happiness Score')
plt.title('Happiness Score vs Generosity')
plt.show()

# Extra Task 1 code
plt.scatter(df['Generosity'], df['Healthy life expectancy at birth'], color='purple')
plt.xlabel('Generosity')
plt.ylabel('Healthy Life Expectancy at Birth')
plt.title('Generosity vs Healthy Life Expectancy at Birth')
plt.show()

# Extra Task 2 code
plt.scatter(df['Social support'], df['Freedom to make life choices'], color='yellow')
plt.xlabel('Social Support')
plt.ylabel('Freedom to Make Life Choices')
plt.title('Social Support vs Freedom to Make Life Choices')
plt.show()